name: head

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=COMMIT_HASH::${GITHUB_SHA:0:7}

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          MOD_VERSION: git-${{ steps.vars.outputs.COMMIT_HASH }}

      - uses: actions/upload-artifact@v2
        with:
          name: adicrate ${{ steps.vars.outputs.COMMIT_HASH }}
          path: "./build/libs/**.jar"
